version: "3"
services:
  ####################
    ## Nginx Proxy
  #####################
  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 3002:3002
      - 3000:3000
      - 3001:3001
    depends_on: 
      - mono-app-1
      - mono-app-2
      - nextjs-application
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/nginx.crt:/etc/nginx/nginx.crt
      - ./nginx/nginx.key:/etc/nginx/nginx.key
  
    
  nextjs-application:
    container_name: nextjs-application
    build:
      context: .
      dockerfile: nextjs-application/Dockerfile
    restart: always
    # ports:
    #   - 3000:3000

  mono-app-1:
    container_name: mono-app-1
    build:
      context: .
      dockerfile: nest-mono-applications/Dockerfile
      args:
        - APP=mono-app-1
    restart: always
    # ports:  
    #   - 3001:3000

  mono-app-2:
    container_name: mono-app-2
    build:
      context: .
      dockerfile: nest-mono-applications/Dockerfile
      args:
        - APP=mono-app-2
    restart: always
    # ports:
    #   - 3002:3000

